### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cxhernandez** [rmcgibbo/clusterLP-MPI#1]
trajid seems to be out of range of  the trajectory_files array. This error only happens in certain cases, however, so it might just be some sort of weird exception to the logic in line 256.

``` python
256    trajid = np.max(np.where(centers[i][1] >= cumulative_lengths)[0])
257    frame = centers[i][1] - cumulative_lengths[trajid]
258    trj = trajectory_files[trajid]
```

**Comment by rmcgibbo** [comment]
I figured out the issue. Will commit a fix shortly.

**Comment by rmcgibbo** [comment]
Sorry for all of the messed up saving of the results to disk.

I'm pretty sure it's fixed now. I added a test that creates 10 random trajectories with random lengths, and then clusters them using between 1 and 10 mpi processes, and ensures that the final output files are all the same, regardless of the # of mpi processors used. It passes.

**Comment by cxhernandez** [comment]
Thanks Robert!
